### ISSUE TITLE
Filter by skills

### ISSUE THREAD

**Issue by Sobieck** [O4epegb/dcss-stats#1]
I'm frequently try to build a character around a type of weapon or skill. 

For instance, I may want to make a character who is a unarmed specialist who worships Wu Jian so I go looking for morgues with unarmed trained. I see in the UI there are the top skills displayed plus the letters are red if it is maxed. That works really well, but as a little improvement it'd be great to be able to filter based on skill just to narrow the results further. 

If this costs any time on the back end it probably isn't worth it. But if it could be done of the front end it'd be great. 

Anyways, thanks for building this website. I used it all the time and it has really helped improve my game.

**Comment by O4epegb** [comment]
Nice idea, thanks for suggestion! I actually have been thinking about similar stuff for the last couple of weeks. I also want to add a tab with skills win rate info, so you could see which skills are most used and etc. 

> Anyways, thanks for building this website. I used it all the time and it has really helped improve my game.

Thank you for using it 😄

**Comment by O4epegb** [comment]
Implemented basic filters 😄 

https://github.com/O4epegb/dcss-stats/commit/227583c20afd55e5728ac5c023c418f20ac9e0f1
