### ISSUE TITLE
"Greater player" is misnamed as "greatest player"

### ISSUE THREAD

**Issue by powerbf** [O4epegb/dcss-stats#2]
The stats page calls winning with all species and all classes "greatest player". This is actually "greater player".  "Greatest player" means winning with all playable combos.

See here: [https://loom.shalott.org/learndb.html](https://loom.shalott.org/learndb.html)

Also the below answers from the discord bot:

MrDizzy — Today at 09:58
??greaterplayer
Yiufbot BOT — Today at 09:58
greaterplayer[1/2]: Players who have won every currently available to play race and class. Lifetime membership once you get in!
MrDizzy — Today at 09:58
??greatestplayers
Yiufbot BOT — Today at 09:58
greatestplayers[1/1]: Players who have won every currently available to play combo. Lifetime membership once you get in!

**Comment by O4epegb** [comment]
How would you call the one who won all the backgrounds/classes then?

**Comment by powerbf** [comment]
What about "solid player"?

**Comment by O4epegb** [comment]
Renamed to Great/Grand/Greater :)
